### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by Jutho** [JuliaCollections/LRUCache.jl#12]
Based on this nice package, I developed a thread safe version, which also allows to use e.g. the total size of all objects rather than the number of objects as criterion for maximum size. Repository is here: https://github.com/Jutho/ThreadSafeLRUCache.jl

While I did change the implementation quite a bit, the basic idea and algorithms are still the same and strongly based on this package. Can I register ThreadSafeLRUCache.jl as an independent package, or should I prepare a PR into this package?

**Comment by jcrist** [comment]
Since they're so similar, I'd say it should be a PR here. That said, I wrote this a few years ago when I was heavily using Julia, and I no longer am. I'd be happy to merge a PR, and even more happy to give you permissions to maintain things here yourself if you'd be interested.

**Comment by Jutho** [comment]
Thanks for the response. As I was under the impression that this package was somewhat abandoned (no commits in almost a year, but that could also just indicate its perfection) , I was not expecting a quick response and already launched the registration process just half an hour ago:
https://github.com/JuliaRegistries/General/pull/2048

However, as this will sit around for some hours/days, I can easily cancel it.

That being said, my implementation has changed quite a bit (mostly also renaming things) and thus would represent a drastic change. I did not attempt to minimise the number of changes to those that were strictly required. I am fine with taking over maintenance of this package, but would need to sort out if my implementation leads to any breaking changes etc.

In particular, I removed / did not take over the `@get!` macro. I think most problems with anonymous functions are no longer around.

**Comment by jcrist** [comment]
> no commits in almost a year, but that could also just indicate its perfection

Indeed, this is a pretty simple datastructure, only maintenance is keeping up with Julia language changes.

> In particular, I removed / did not take over the @get! macro. I think most problems with anonymous functions are no longer around.

That's likely.

> That being said, my implementation has changed quite a bit (mostly also renaming things) and thus would represent a drastic change. 

As long as the public interface remains the same and the tests pass, there should be no issues. It looks like your implementation is separate from the one here, but could maybe share some internals (or maybe not 🤷‍♂). My main goal here is:

- Prevent package fragmentation. This is already in `JuliaCollections`, and does have some users.
- Get someone who actively uses Julia to take over this package :).

**Comment by Jutho** [comment]
OK, that's a admirable goal. Do you have any idea of packages depending on LRUCache? I tried to quickly google for a package dependency tree, but did not find any helpful results. Coordinating with current users might be a good idea.

**Comment by jcrist** [comment]
> Do you have any idea of packages depending on LRUCache?

No, and a quick google didn't turn up an easy way to find downstream dependencies. At one point it was used by `Parquet.jl`, but that seems to have changed.

**Comment by Jutho** [comment]
Github search helped: 
https://github.com/search?l=&p=2&q=%22using+LRUCache%22+language%3AJulia&type=Code

I found:
* ArrayAllez.jl by @mcabbott
* RLESUtils.jl by @sisl
* WeibullCount.jl by @torfjelde
* TimedPlayBack.jl and Weber.jl by @haberdashPI

Maybe these authors can quickly look if they are ok with me taking over ownership and making some changes to the interface (via proper deprecation in an intermediate version).

In summary, I added the following features:
* Thread safety
* Specify a custom function to measure the size of objects in the cache and thus limit the total size of all items (values), rather than just counting the number of items.

And made the following interface changes:
* abandon `@get!` macro, as anonymous functions are mostly without problems in current day Julia
* specify `maxsize` via required keyword argument instead of just single positional argument (since this is not compatible with interface of an `AbstractDict`, which takes as positional argument an iterator over key-value pairs. 
* Do not pun on using `Base.resize!` but use a new function `setsize!`, since the meaning of the maximal size of the LRUCache is not the same as its length.

**Comment by jcrist** [comment]
To be clear, I'm not saying you should replace this package, I'm saying your type could be added as another implementation of a common interface.

> And made the following interface changes:

Those changes all make sense to me.

**Comment by haberdashPI** [comment]
I have no problem with the proposed changes. (I'm not actively maintaining either of those packages).

**Comment by mcabbott** [comment]
No objection here, I can update to whatever you settle on. Thanks for searching!

**Comment by Jutho** [comment]
Hi @jcrist , not sure if we can still expect an answer of the other two package authors (it is holiday period of course), but I would like not to wait too long with making the changes should that I can proceed with the packages that I am working on and which depend on this.

So if you agree with me becoming a co-author/maintainer of this package, I will gratefully but eagerly await your invitation for access. :-)

**Comment by jcrist** [comment]
Done, you should have an invite in your email.

**Comment by Jutho** [comment]
Hi @jcrist , I was thrown off the JuliaCollections team and as a collaborator of this package because I did not have two-factor authentication on Github enabled. I fixed this now, could you invite me again? My apologies for the overhead.
