### ISSUE TITLE
CacheInfo reporting

### ISSUE THREAD

**Issue by kshyatt** [JuliaCollections/LRUCache.jl#28]
Python's `functools` implements an LRU cache which has a method to report:
- Number of hits 
- Number of misses
- Maximum cache size
- Current cache size

Is this something that would be useful as a feature?

**Comment by Jutho** [comment]
If it is possible without overhead, I would think so. Also good to have an established interface to draw inspiration from. Feel free to make a PR if you like.

**Comment by ericphanson** [comment]
I gave it a go in https://github.com/JuliaCollections/LRUCache.jl/pull/43, perhaps you could take a look @kshyatt? In particular I’m not totally sure if only counting hits/misses on get/get! is the right approach or not.
