### ISSUE TITLE
Maintenance of this package

### ISSUE THREAD

**Issue by davidanthoff** [JuliaCollections/LRUCache.jl#6]
It would be great if we found a way to keep this package maintained. My understanding is that @jcrist is no longer working with julia, but is willing to transfer the repo to someone else, which seems the most sensible plan to me.

Maybe either to @tk3369 or the JuliaComputing account? I have the same goal as @tk3369: I would love to get Parquet.jl to work, and it depends on LRUCache.jl @tanmaykm given that you guys also have the Parquet.jl repo, would it make sense to move this repo into JuliaComputing and maybe give @tk3369 commit rights there given that he wants to help with this?

We could also leave it under @jcrist's account and he could give various folks commit rights, by I think it would be cumbersome. Whenever we want to change things like CI etc. he would have to be involved, which seems a huge ask from someone who is no longer interested in this.

CC @ViralBShah

**Comment by tanmaykm** [comment]
I have made changes to Parquet.jl (in a branch as of now) to use [MemPool.jl](https://github.com/JuliaComputing/MemPool.jl) instead. I can submit a PR soon.

LRUCache.jl may be useful in other places though, so moving / giving access to the repo may still be worthwhile.

**Comment by ViralBShah** [comment]
It would great to transfer to a community org for joint management.

**Comment by jcrist** [comment]
Apologies for my lack of response here. I'm happy to move this project to whatever org seems a good fit. Please let me know where makes sense.

**Comment by ViralBShah** [comment]
Thank you. @ararslan Can you suggest where might we move this? Maybe to `JuliaData`?

**Comment by ararslan** [comment]
I'd say JuliaCollections. If that seems reasonable, I can give @jcrist the appropriate permissions to transfer this LRUCache to that organization.

**Comment by ViralBShah** [comment]
+1

**Comment by ararslan** [comment]
Okay, @jcrist I've invited you to the JuliaCollections organization with owner privileges, which allows transferring to/from the organization. You can transfer this repository in settings.

**Comment by jcrist** [comment]
Thanks @ararslan. The package has been moved to JuliaCollections. Closing.

**Comment by ViralBShah** [comment]
Do we need to update METADATA too?

**Comment by ararslan** [comment]
Ah yes. It should still work as-is due to GitHub redirects, but it's always good to have METADATA pointing to the right place. I can submit a PR for that in a bit.
